2014/06/06 13:21:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "invoices".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/invoices
---
2014/06/09 13:53:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
<<<<<<< HEAD
2014/06/09 14:17:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery-ui-1.9.2.css".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery-ui-1....')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery-ui-1.9.2.css
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 14:18:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery-ui-1.9.2.css".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery-ui-1....')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery-ui-1.9.2.css
HTTP_REFERER=http://crm.loc/invoices
=======
2014/06/09 14:32:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
>>>>>>> 3d3ca804ba83a562770c7dec30988c5e495e9c69
---
2014/06/09 15:00:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/module.invoice/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/module.invoi...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/module.invoice/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:04:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/module.invoice/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/module.invoi...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/module.invoice/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:07:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_f6f6f6_1x400.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_f6f6f6_1x400.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-icons_ffffff_256x240.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-i...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-icons_ffffff_256x240.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_gloss-wave_35_f6a828_500x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_gloss-wave_35_f6a828_500x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-icons_ef8c08_256x240.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-i...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-icons_ef8c08_256x240.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:10:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_fdf5ce_1x400.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_fdf5ce_1x400.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:11:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_65_ffffff_1x400.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_65_ffffff_1x400.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:50:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/09 15:51:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_gloss-wave_35_f6a828_500x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_gloss-wave_35_f6a828_500x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_f6f6f6_1x400.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_f6f6f6_1x400.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-icons_ffffff_256x240.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-i...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-icons_ffffff_256x240.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_fdf5ce_1x400.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_fdf5ce_1x400.png
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:51:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 15:52:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 16:01:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "invoices/invoices/list/listall".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/invoic...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/invoices/invoices/list/listall
---
2014/06/09 16:01:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/index.php/invoices/list/listall
---
2014/06/09 16:02:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/index.php/invoices/list/listall
---
2014/06/09 16:03:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/index.php/invoices
---
2014/06/09 16:03:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 16:03:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices
---
2014/06/09 16:03:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/invoices/list/index
---
2014/06/09 16:03:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.loc/index.php/invoices/list/listall
---
2014/06/09 16:12:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\crm\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\_GIT\crm\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\crm\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://crm.loc/invoices/list/listall/test/5
---
2014/06/09 18:05:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/09 18:05:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices/list/listall
---
2014/06/09 18:49:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/09 18:49:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices/list/listall
---
2014/06/09 18:50:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices/list/listall
---
2014/06/09 18:55:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices/list/listall
---
2014/06/09 19:11:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices/list/listall
---
2014/06/09 19:12:29 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "user" is not defined in active record class "Ops".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:226
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(296): CActiveFinder->buildJoinTree(Object(CJoinElement), 'user')
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(909): CActiveFinder->__construct(Object(Ops), Array)
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1355): CActiveRecord->getActiveFinder(Array)
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(13): CActiveRecord->findAll()
#6 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#7 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#12 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#14 {main}
REQUEST_URI=/invoices/
---
2014/06/09 19:13:07 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (13)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:13:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (13)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:13:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(13): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices/
---
2014/06/09 19:26:42 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (66)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:26:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (66)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:26:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_number" AS "t0_c1", 't'."user_id" AS "t0_c2", 't'."date" AS "t0_c3", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'ops' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(66): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:26:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/09 19:29:06 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Ops" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(66): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:35:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://fcrm.local/invoices
---
2014/06/09 19:39:07 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "invoices".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:40:06 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "invoices".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:41:00 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:41:00 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 19:41:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:51:06 [error] [exception.CException] exception 'CException' with message 'Property "Invoices.ops_number" is not defined.' in C:\OpenServer\domains\fcrm.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ops_number')
#1 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\views\list\index.php(37): CActiveRecord->__get('ops_number')
#2 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#3 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(69): CController->render('index', Array)
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:52:28 [error] [exception.CException] exception 'CException' with message 'Property "Invoices.ops_number" is not defined.' in C:\OpenServer\domains\fcrm.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ops_number')
#1 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\views\list\index.php(37): CActiveRecord->__get('ops_number')
#2 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#3 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(69): CController->render('index', Array)
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:52:33 [error] [exception.CException] exception 'CException' with message 'Property "Invoices.ops_number" is not defined.' in C:\OpenServer\domains\fcrm.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ops_number')
#1 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\views\list\index.php(37): CActiveRecord->__get('ops_number')
#2 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#3 C:\OpenServer\domains\fcrm.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(69): CController->render('index', Array)
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:53:14 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "ops" in active record class "Invoices" is specified with an invalid foreign key "ops_id". There is no such column in the table "ops".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 19:59:48 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\fcrm.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(182): model()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(230): CActiveFinder->getModel()
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(296): CActiveFinder->buildJoinTree()
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree()
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(909): CActiveFinder->__construct()
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1355): Invoices->getActiveFinder()
#7 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): Invoices->query()
#8 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): Invoices->findAll()
#9 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): ListController->runAction()
#12 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): ListController->runActionWithFilters()
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): ListController->run()
#14 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\OpenServer\domains\fcrm.local\index.php(36): CWebApplication->run()
REQUEST_URI=/invoices
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:00:57 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\fcrm.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(182): model()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(230): CActiveFinder->getModel()
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(296): CActiveFinder->buildJoinTree()
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree()
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(909): CActiveFinder->__construct()
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1355): Invoices->getActiveFinder()
#7 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): Invoices->query()
#8 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): Invoices->findAll()
#9 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): ListController->runAction()
#12 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): ListController->runActionWithFilters()
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): ListController->run()
#14 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\OpenServer\domains\fcrm.local\index.php(36): CWebApplication->run()
REQUEST_URI=/invoices
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:01:58 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\fcrm.local\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(182): model()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(230): CActiveFinder->getModel()
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(296): CActiveFinder->buildJoinTree()
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree()
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(909): CActiveFinder->__construct()
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1355): Invoices->getActiveFinder()
#7 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): Invoices->query()
#8 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): Invoices->findAll()
#9 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): ListController->runAction()
#12 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): ListController->runActionWithFilters()
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): ListController->run()
#14 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\OpenServer\domains\fcrm.local\index.php(36): CWebApplication->run()
REQUEST_URI=/invoices
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:02:20 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:02:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:02:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:03:35 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:04:22 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "user" is not defined in active record class "Invoices".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:226
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(296): CActiveFinder->buildJoinTree(Object(CJoinElement), 'user')
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(909): CActiveFinder->__construct(Object(Invoices), Array)
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1355): CActiveRecord->getActiveFinder(Array)
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#6 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#7 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#12 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#14 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:04:45 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:11:46 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:11:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:11:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:12:58 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:12:58 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:12:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:13:34 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") 
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:13:34 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") .
in C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\fcrm.local\index.php (36)
2014/06/09 20:13:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2", 'ops'."id" AS "t2_c0", 'ops'."ops_number" AS "t2_c1", 'ops'."user_id" AS "t2_c2", 'ops'."date" AS "t2_c3" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."")  LEFT OUTER JOIN 'ops' 'ops' ON ('t'."ops_id"='ops'."id") ' in C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:15:29 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 20:16:20 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\fcrm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\fcrm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\fcrm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\fcrm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\fcrm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\fcrm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\fcrm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
