2014/06/09 22:47:28 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:48:27 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:48:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:48:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:53:40 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:53:40 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:53:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:54:34 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:54:34 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:54:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:54:36 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:54:36 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:54:36 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:55:32 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:55:32 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 22:55:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: user.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'user'."id" AS "t1_c0", 'user'."fname" AS "t1_c1", 'user'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'user' ON ('t'."user_id"='user'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:55:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/09 22:56:42 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "user" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 22:59:25 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "users" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:00:20 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "users" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:00:21 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "users" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:01:12 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "users" in active record class "Invoices" is specified with an invalid foreign key "user_id". There is no such column in the table "users".' in C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php:1096
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1067): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(1295): CJoinElement->getJoinCondition()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(790): CJoinQuery->join(Object(CJoinElement))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(435): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#8 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#14 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#16 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:03:16 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:03:16 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:03:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:04:01 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:04:40 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:40 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:04:41 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:41 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:04:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:05:07 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:05:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:05:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/09 23:05:08 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") 
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:05:08 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") .
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (67)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/09 23:05:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such column: users.. The SQL statement executed was: SELECT 't'."id" AS "t0_c0", 't'."ops_id" AS "t0_c1", 't'."date" AS "t0_c2", 't'."user_id" AS "t0_c3", 't'."file_name" AS "t0_c4", 'users'."id" AS "t1_c0", 'users'."fname" AS "t1_c1", 'users'."lname" AS "t1_c2" FROM 'invoices' 't'  LEFT OUTER JOIN 'users' 'users' ON ('t'."user_id"='users'."") ' in C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(803): CDbCommand->queryAll()
#2 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(437): CJoinElement->runQuery(Object(CJoinQuery))
#3 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#4 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1356): CActiveFinder->query(Object(CDbCriteria), true)
#5 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(1470): CActiveRecord->query(Object(CDbCriteria), true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(67): CActiveRecord->findAll()
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/10 00:18:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/06/10 00:18:46 [error] [exception.CException] exception 'CException' with message 'Property "Invoices.user" is not defined.' in C:\OpenServer\domains\crm.local\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\db\ar\CActiveRecord.php(145): CComponent->__get('user')
#1 C:\OpenServer\domains\crm.local\protected\modules\invoices\views\list\index.php(39): CActiveRecord->__get('user')
#2 C:\OpenServer\domains\crm.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#3 C:\OpenServer\domains\crm.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\crm.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\crm.local\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php(69): CController->render('index', Array)
#7 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(49): ListController->actionIndex()
#8 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/i...')
#13 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#15 {main}
REQUEST_URI=/invoices
---
2014/06/10 00:19:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 00:48:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "link/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('link/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/link/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 00:50:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "link/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('link/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/link/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:08:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "link/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('link/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/link/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:10:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "link/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('link/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/link/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:11:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "list/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('list/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/list/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:11:49 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\OpenServer\domains\crm.local\framework\web\CController.php:336
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): CController->run('ops')
#4 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('invoices/list/o...')
#5 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#7 {main}
REQUEST_URI=/invoices/list/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:15:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/list/ops".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/list/ops')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/invoices/list/ops/1
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 01:24:55 [error] [php] Object of class Ops could not be converted to string (C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php:74)
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 C:\OpenServer\domains\crm.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 C:\OpenServer\domains\crm.local\framework\web\CController.php(286): ListController->runAction()
#3 C:\OpenServer\domains\crm.local\framework\web\CController.php(265): ListController->runActionWithFilters()
#4 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(282): ListController->run()
#5 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 C:\OpenServer\domains\crm.local\index.php(36): CWebApplication->run()
REQUEST_URI=/invoices/list/ops/2
in C:\OpenServer\domains\crm.local\protected\modules\invoices\controllers\ListController.php (74)
in C:\OpenServer\domains\crm.local\index.php (36)
2014/06/10 01:39:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://crm.local/invoices
---
2014/06/10 02:17:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-icons_ffffff_256x240.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-i...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-icons_ffffff_256x240.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_f6f6f6_1x400.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_f6f6f6_1x400.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_gloss-wave_35_f6a828_500x100.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_gloss-wave_35_f6a828_500x100.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_100_fdf5ce_1x400.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_100_fdf5ce_1x400.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
2014/06/10 02:17:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/images/ui-bg_glass_65_ffffff_1x400.png".' in C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\crm.local\framework\web\CWebApplication.php(141): CWebApplication->runController('css/images/ui-b...')
#1 C:\OpenServer\domains\crm.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\crm.local\index.php(36): CApplication->run()
#3 {main}
REQUEST_URI=/css/images/ui-bg_glass_65_ffffff_1x400.png
HTTP_REFERER=http://crm.local/css/jquery-ui-1.9.2.css
---
